### ISSUE TITLE
特定のウインドウサイズの場合操作不可となるオプション設定がある。

### ISSUE THREAD

**Issue by wataru5123** [onitama/mucom88#1]
掲題の通り、増設されたSCCI設定のボタンですが ウインドウサイズが800X600の際に
下部ログ画面に被さる形で一見表示されますがボタン自体は操作不可となる現象を確認しています。

![default](https://user-images.githubusercontent.com/5012894/50672327-bb5ae080-101a-11e9-8340-5dba3dd8bea5.jpg)

**Comment by onitama** [comment]
ご報告ありがとうございます。次のバージョンで修正されます。
