### ISSUE TITLE
updated mucom88 emits #Unknown message and cannot compile mucom88win_yk2mml190107/BARE2_MML .muc modules on x86_64 GNU/Linux Lubuntu

### ISSUE THREAD

**Issue by gzaffin** [onitama/mucom88#15]
Hi,
I cannot compile some .muc modules taken from [MUCOM88 Windows page](https://onitama.tv/mucom88/)  , its sample archive on a Lubuntu x86_64 machine.
Compilation results in error and cannot complete.
I don't understand error message saying "FM Voice not found".
See attached screenshot for details.
![2020-04-05-122352_656x465_scrot](https://user-images.githubusercontent.com/16971874/78472497-93848c00-7739-11ea-9901-80b54f97afc4.png)
![2020-04-05-122349_656x465_scrot](https://user-images.githubusercontent.com/16971874/78472500-97181300-7739-11ea-9cca-c8f4fa41a8a5.png)

**Comment by onitama** [comment]
I made a compilation fix for the Linux version in the latest master repository.
I'm not getting any errors here with bare03.muc.
Do you still have a problem with that?

**Comment by gzaffin** [comment]
Terrific job indeed! Compilation of bare03.muc is perfectly working.

![2020-04-09-235104_656x465_scrot](https://user-images.githubusercontent.com/16971874/78944005-3f710300-7abd-11ea-9d27-ac5dca7cd2f9.png)
![2020-04-09-235214_656x465_scrot](https://user-images.githubusercontent.com/16971874/78944021-46981100-7abd-11ea-9d11-d211e8bee0a5.png)
![2020-04-09-235222_656x465_scrot](https://user-images.githubusercontent.com/16971874/78944047-53b50000-7abd-11ea-8de0-56fc7fa84683.png)

**Comment by gzaffin** [comment]
And again good results when compiling bare09.muc, bare12.muc, bare16.muc and bare75.muc.
I don't understand why bare04.muc and bare21.muc do not compile.
![2020-04-10-000049_656x465_scrot](https://user-images.githubusercontent.com/16971874/78944760-ec984b00-7abe-11ea-842d-a164f0d8d64b.png)
![2020-04-10-000102_656x465_scrot](https://user-images.githubusercontent.com/16971874/78944766-f15cff00-7abe-11ea-9a5a-0a1550cd8165.png)

**Comment by onitama** [comment]
Thanks for your testing.
bare04.muc and bare21.muc uses @"name" style MML syntax.
This is a problem that comes from the UTF-8 character code.
I modified the code to work correctly if the MML is stored in UTF-8.
I hope this works.

**Comment by gzaffin** [comment]
Thank You Mr. onitama.
I did as You suggested. I converted MML source file to UTF-8 encoding like this:
![2020-04-10-182454_656x465_scrot](https://user-images.githubusercontent.com/16971874/79006176-ddfe7200-7b58-11ea-9203-72a98937e343.png)

then I cleaned converted MML source because during conversion a Yen sign '¥' with UNICODE UTF-8 is 'C2 A5' has taken place of backslash '\' and then compile cleaned MML source with mucom88. And everything goes well!

![2020-04-10-182556_656x465_scrot](https://user-images.githubusercontent.com/16971874/79006481-8f050c80-7b59-11ea-955d-a2ec6ca31b29.png)
![2020-04-10-182633_656x465_scrot](https://user-images.githubusercontent.com/16971874/79006484-90363980-7b59-11ea-86fa-9ec6f71581b5.png)

I did cleaning of Yen sign '¥' with a simple C program, but it can be everything, some script language, like Python, everything that works for the purpose.
`
#include <stdio.h>

int main (int argc, char * argv[]) {
	FILE * inpF, * outF;
	int currByte;

	if( argc != 3 ) {
		printf("%s must be called with one input filename and one output filename.\n", argv[0] );
		return 1;
	} else {
		inpF = fopen( argv[1], "rb" );
		if( (FILE *)NULL == inpF ) {
			return 1;
		} else {
			outF = fopen( argv[2], "wb" );
			if( (FILE *)NULL == outF ) {
				if( (FILE *)NULL != inpF ) {
					fclose(inpF);
				}
				return 1;
			}
		}

		while( EOF != ( currByte = getc(inpF) ) ) {
			if( 0xC2 == currByte ) {
				int nextByte = getc(inpF);
				if ( EOF == nextByte ) {
					putc ( currByte, outF );
					break;
				} else if ( 0xA5 == nextByte ) {
					putc( 0x5C, outF );
				} else {
					putc ( currByte, outF );
					putc ( nextByte, outF );
				}
			} else {
				putc( currByte, outF );
			}
		}
		fclose( inpF );
		fclose( outF );
	}

	return 0;
}

`
