### ISSUE TITLE
Program crashes at start if configuration file is corrupted or invalid.

### ISSUE THREAD

**Issue by 7l-oliveira** [onitama/mucom88#17]
Due to some error not related to mucom88win (power out during mucom88win use maybe) the mucom88win.ini file became filled with zero value characters instead of normal configuration text and the application stopped starting, faulting with divide by zero error and closing off.

If the application detect the .ini file is bad, warn the user, delete the bad file and make a new one it would prevent this problem I believe.

Took me a few months until I had the idea of checking if the .ini file at %appdata% was corrupted. (look the ini file date). I added the bad file in so you can try reproduce the problem.

[report.zip](https://github.com/onitama/mucom88/files/5394886/report.zip)

**Comment by onitama** [comment]
Thanks for the report.
This bug will be fixed in the next version.
