### ISSUE TITLE
Fix compilation on linux

### ISSUE THREAD

**Issue by cyberic99** [onitama/mucom88#18]
Hello!

I had a few adjustment to make in order to compile mucom88 on linux:

This patch:
```patch
diff --git a/src/adpcm.h b/src/adpcm.h
index 01f2eee..dbbb0dd 100644
--- a/src/adpcm.h
+++ b/src/adpcm.h
@@ -15,6 +15,11 @@ typedef unsigned long DWORD;
 typedef unsigned short WORD;
 #endif
 
+#ifndef DWORD_PTR
+typedef unsigned long ULONG_PTR;
+typedef ULONG_PTR DWORD_PTR;
+#endif
+
```

prevents this error
```
adpcm.cpp: In member function ‘BYTE* Adpcm::waveToAdpcm(void*, DWORD, DWORD&, DWORD, DWORD)’:
adpcm.cpp:25:57: error: ‘DWORD_PTR’ does not name a type
   25 |  pChunk = reinterpret_cast<CHUNK_HED*>(reinterpret_cast<DWORD_PTR>(pChunk) + 4);
      |                                                         ^~~~~~~~~
adpcm.cpp:28:25: error: ‘DWORD_PTR’ does not name a type
   28 |  while(reinterpret_cast<DWORD_PTR>(pChunk) < reinterpret_cast<DWORD_PTR>(pData) + dSize)
      |                         ^~~~~~~~~
adpcm.cpp:28:63: error: ‘DWORD_PTR’ does not name a type
   28 |  while(reinterpret_cast<DWORD_PTR>(pChunk) < reinterpret_cast<DWORD_PTR>(pData) + dSize)
      |                                                               ^~~~~~~~~
adpcm.cpp:41:58: error: ‘DWORD_PTR’ does not name a type
   41 |   pChunk = reinterpret_cast<CHUNK_HED*>(reinterpret_cast<DWORD_PTR>(pChunk) + pChunk->dChunkSize + 8);
      |                                                          ^~~~~~~~~
make: *** [Makefile:222: objs/adpcm.o] Error 1
```

Also, my ``sdl-config`` (version 1.2.15) file doesn't not have the ``--static-libs`` switch.

Also, ``STATIC`` is enabled by default, but the built binaries do not seem to be static

Tell me if I can provide any help with more tests, or if you want me to do some pull requests

Thx!

**Comment by gzaffin** [comment]
cyberic99, You are right about compilation problem on GNU/Linux, at least in my Lubuntu machine.


For the code change, You should not check for the DWORD_PTR definition with a #ifdef/#ifndef #endif strategy, in lines 6-11 of Your patch.

We know that DWORD_PTR is defined for Window in BaseTsd.h
https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

so it is better to either use define guard of BaseTsd.h or go straight with define guard of Windows, like this
```

+#ifndef _WIN32
+typedef unsigned long ULONG_PTR;
+typedef ULONG_PTR DWORD_PTR;
+#endif
+
```

**Comment by cyberic99** [comment]
You're right @gzaffin , thanks. @onitama tell me if you would like me to make a pull request.
