### ISSUE TITLE
MMLリファレンスの誤り : Eコマンド

### ISSUE THREAD

**Issue by MUCOM88** [onitama/mucom88#2]
Eコマンドの説明で誤りと思われる個所がありましたのでご報告致します。

<誤> [SSG] ソフトウェアエンベロープ(En1,n2,n3,n4,n5,n6) AL,AR,DR,SR,SL,RR
　↓
<正> [SSG] ソフトウェアエンベロープ(En1,n2,n3,n4,n5,n6) AL,AR,DR,SL,SR,RR

※SRとSLの説明が逆と思われます。

**Comment by onitama** [comment]
修正しました。ありがとうございます。
