### ISSUE TITLE
MMLリファレンスの誤り：リズム音源のvコマンド

### ISSUE THREAD

**Issue by MUCOM88** [onitama/mucom88#3]
「MML内部」の項のリズム音源のvコマンドの説明で誤りと思われる箇所がありましたのでご報告致します。

<誤> [リズム] vn1,n2,n3,n4,n5,n6,n7 (全体,BD,SD,HH,CY,TM,RY)
　↓
<正> [リズム] vn1,n2,n3,n4,n5,n6,n7 (全体,BD,SD,CY,HH,TM,RY)

HHとCYの順が逆と思われます。

**Comment by onitama** [comment]
修正対応しました。
