### ISSUE TITLE
MMLリファレンスの誤り：oコマンド

### ISSUE THREAD

**Issue by MUCOM88** [onitama/mucom88#4]
「MML内部」の項のoコマンドの説明で誤りと思われる箇所がありましたのでご報告致します。

<誤> [FM/SSG] オクターブ絶対指定(o1～o8, デフォルトo4)
　↓
<正> [FM/SSG] オクターブ絶対指定(o1～o8, デフォルトo6)

オクターブ指定のデフォルト値はo6と思われます。(ちなみにADPCMも同様です)

**Comment by onitama** [comment]
修正対応しました。
