### ISSUE TITLE
MMLリファレンスの誤り：相対音量指定「) (」コマンド

### ISSUE THREAD

**Issue by MUCOM88** [onitama/mucom88#6]
「MML内部」の項の相対音量指定コマンドの説明で誤りと思われる箇所がありましたのでご報告致します。(五月雨ですみません)

<誤>
)  音量相対指定(上げ) 16段階
(  音量相対指定(下げ) 16段階

16段階とありますが、ADPCMの場合は256段階でnの値も内部処理的には0～255で指定が可能と思われます。

**Comment by onitama** [comment]
修正対応しました。
