### ISSUE TITLE
MMLリファレンスの補足：Rコマンド

### ISSUE THREAD

**Issue by MUCOM88** [onitama/mucom88#7]
誤りと言う訳ではありませんが、「MML内部」の項のリバーブコマンドで説明がやや不足していると感じましたので補足致します。

<指摘箇所>
[FM/SSG] リバーブ Rn で音量の加減値を指定 (nは負の値も指定可) 
キーオフ時、キーオフする代わりに現在の音量の約1/3に設定して発音を続ける。

現在の音量の約1/3とありますが、FMとSSGではやや様子が異なるようです。
FMの場合：リバーブ時の音量=int((現在の音量+リバーブ値+4)/2)-4
SSGの場合：リバーブ時の音量=int((現在の音量+リバーブ値)/2)

**Comment by onitama** [comment]
修正対応しました。
