### ISSUE TITLE
【要望】FmToneEditor.exeの機能について

### ISSUE THREAD

**Issue by overgo256** [onitama/mucom88#8]
スタンドアロン版の音色エディタ（mucom88win190323同梱版 CRC32: 371C602C、以下「FmToneEditor.exe」）について要望を３点、優先順に書かせていただきます。

［１．起動時にvoice.datを読み込こむオプションがほしい］
現在FmToneEditor.exeを起動するとアルゴリズム0のベース音が1つある状態ですが、カレントディレクトリにvoice.datがある場合は標準音色として読み込むオプションが設定メニューにほしいです。
上記オプションが有効時、voice.datが存在しない場合に無視するか明示的にエラーダイアログを表示するかはお任せいたします。

［２．Algorithmのオペレータ結合イメージにAL番号を併記してほしい］
現在FmToneEditor.exeの画面右上にプレビュー表示されているアルゴリズムの結合イメージですが、入力パラメータの表示とは別にキャプションの「Algorism [0]」「Algorism: 0」といったようにアルゴリズムの番号を併記していただけませんでしょうか？
Ctrl+カーソルキーで音色を連続して変更する場合、視線は変化が大きい画面右上に注目することになるためキャプションにもAL番号が併記してあると良いかと思います。

［３．パラメータ入力の確定時、音色プレビューに即時反映してほしい］
現在FmToneEditor.exeの各パラメータの手動入力で Enter（編集開始） → 数値入力 → Enter（確定）の手順を踏んでパラメータ値を更新もエンベロープの表示が変化するのみで音色プレビュー（zx～nm,）に反映されません。
実際のところPageUp／PageDownによる微調整的なパラメータ変更の方が使用頻度が高いので、優先度は低めで構いません。

【補足】FmToneEditoe.txtの誤表記について
17行目 Enterキーの説明：編集対象のパラメータが直接入力モードになします。
こちらは「入力モードになります」が正でしょうか？

以上、よろしくお願いいたします。

**Comment by onitama** [comment]
ご意見ありがとうございます。
機能の検討をしたいと思います。
